core/urls.py
from django.urls import path

from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('buy/', views.buy, name='buy'),
    path('sell/', views.sell, name='sell'),
    path('quote/', views.quote, name='quote'),
    path('history/', views.history, name='history'),
    path('leaderboard/', views.leaderboard, name='leaderboard'),
]

educaitonalStockTracker/urls.py
from django.contrib import admin
from django.urls import path, include # new
from django.conf import settings # new
from django.conf.urls.static import static # new

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')), # new
    path('', include('core.urls')), # new
    path('__debug__/', include('debug_toolbar.urls')), # new
    path('classroom/', include('classroom.urls')), # new
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views
from .forms import LoginForm

app_name = 'user'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='user/login.html', authentication_form=LoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password/', views.CustomPasswordChangeView.as_view(template_name='user/change_password.html', success_url='/'), name='change_password'),
    path('profile/', views.profile, name='profile'),
    path('delete/', views.deleteAccount, name='delete_account')
]

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils import timezone

from classroom.models import Classroom

# Create your models here.

class User(AbstractUser):
    class Role(models.TextChoices):
        STUDENT = 'STUDENT', 'Student'
        TEACHER = 'TEACHER', 'Teacher'
    
    base_role = Role.STUDENT
    
    role = models.CharField(max_length=50, choices=Role.choices, default=base_role)
    passwordTimeSet = models.DateTimeField(blank=True, null=True, default=timezone.now)  

    def __str__(self):
        return self.username

# Create a student when a user is created
@receiver(post_save, sender=User)
def create_student(sender, instance, created, **kwargs):
    if created and instance.role == 'STUDENT':
        Student.objects.create(user=instance)
    
class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    cash = models.DecimalField(max_digits=10, decimal_places=2, default=10000.00)
    total_value = models.DecimalField(max_digits=10, decimal_places=2, default=10000.00)
    xp = models.IntegerField(default=0)
    classroom = models.ForeignKey('classroom.Classroom', on_delete=models.SET_NULL, null=True)
    
    def __str__(self):
        return self.user.username
    
    # xp reward function
    def xpUp(self, xpGain):
        self.xp+=xpGain
        self.save()

# Create a teacher when a user is created
@receiver(post_save, sender=User)
def create_teacher(sender, instance, created, **kwargs):
    if created and instance.role == 'TEACHER':
        Teacher.objects.create(user=instance)

class Teacher(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    
    def __str__(self):
        return self.user.username

user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm

from user.models import User

class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2', 'role']

    username = forms.CharField(max_length=30, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Username',
        'autofocus': 'autofocus',
        }))
    
    email = forms.EmailField(max_length=254, widget=forms.EmailInput(attrs={
        'class': 'form-control',
        'placeholder': 'Email',
        }))
    
    password1 = forms.CharField(max_length=30, widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'placeholder': 'Password',
        }))
    
    password2 = forms.CharField(max_length=30, widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'placeholder': 'Confirm Password',
        }))
    
    role = forms.ChoiceField(choices=User.Role.choices, widget=forms.Select(attrs={
        'class': 'form-control',
        }))

class LoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ['username', 'password']
    
    username = forms.CharField(max_length=30, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Username',
        'autofocus': 'autofocus',
        }))

    password = forms.CharField(max_length=30, widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'placeholder': 'Password',
        }))
    
class PasswordChangingForm(PasswordChangeForm):
    class Meta:
        model = User
        fields = ['old_password', 'new_password1', 'new_password2']

    old_password = forms.CharField(max_length=30, widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'placeholder': 'Old password',
        'autofocus': 'autofocus',
        'type': 'password',
        }))
    
    new_password1 = forms.CharField(max_length=30, widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'placeholder': 'New password',
        'type': 'password',
        }))
    
    new_password2 = forms.CharField(max_length=30, widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'placeholder': 'Confirm new password',
        'type': 'password',
        }))
    

user/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib import messages
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from django.utils import timezone

from .forms import RegisterForm, PasswordChangingForm
from .models import User, Student
# Create your views here.

def register(request):
    # post request means registration form has been submitted
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            # save user to database
            form.save()
            messages.success(request, 'Account created successfully!')
            # check if the user is a student or a teacher
            role = form.cleaned_data['role']
            if role == 'STUDENT':
                return redirect('user:login')
            
            elif role == 'TEACHER':
                return redirect('user:login')
        else:
            return render(request, 'user/register.html', {'form': form})

    form = RegisterForm()
        
    return render(request, 'user/register.html', {'form': form})

@login_required
def profile(request):
    return render(request, 'user/profile.html')

class CustomPasswordChangeView(auth_views.PasswordChangeView):
    template_name = 'user/change_password.html'
    success_url = '/'
    form_class = PasswordChangingForm
    
    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, 'Password changed successfully!')
        # after changing password, set the passwordTimeSet field to now
        # this is used to check if the password is too old
        self.request.user.passwordTimeSet = timezone.now()
        self.request.user.save()
        return response

@login_required
def deleteAccount(request):
    if request.method == 'POST':
        # delete the user from the database
        request.user.delete()
        messages.success(request, 'Account deleted successfully!')
    return redirect('user:login')

user/templates/user/change_password.html
{% extends 'core/base.html' %}

{% block title %}Change Password{% endblock %}
    
{% block content %}
<div>
    <form action="." method="post">
        <div class="form-group"></div>
        {% csrf_token %}
        <div class="mb-3">
            <label class="inline-block mb-2">Old password:</label><br>
            {{ form.old_password }}
        </div>
        <div class="mb-3">
            <label class="inline-block mb-2">New password:</label><br>
            {{ form.new_password1 }}
        </div>
        <div class="mb-3">
            <label class="inline-block mb-2">Confirm new password:</label><br>
            {{ form.new_password2 }}
        </div>
        <!-- Display any form errors -->
        {% for field in form %}
            {% for error in field.errors %}
                <p style="color: red">{{ error }}</p>
            {% endfor %}
        {% endfor %}
        </div>
        <button class="m-3 btn btn-primary" type="submit">Submit</button>
    </form>
</div>
{% endblock %}

user/templates/user/login.html
{% extends 'core/base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
<div>
    <h1>Login</h1>
    <form action="." method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label class="inline-block mb-2">Username:</label><br>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Password:</label><br>
            {{ form.password }}
        </div>
        {% for error in form.non_field_errors %}
            <p style="color: red">{{ error }}</p>
        {% endfor %}
        <button class="btn btn-primary">Login</button>
    </form>
    <p>Don't have an account? <a href="{% url 'user:register' %}">Register</a></p>
</div>
{% endblock %}

user/templates/user/profile.html
{% extends 'core/base.html' %}

{% block title %}Change Password{% endblock %}
    
{% block content %}
<div class="container">
    <div>
        <strong>Username:</strong> {{ request.user.username}}
    </div>
{% if request.user.role == 'STUDENT'%}
    <div>
        <strong>XP:</strong> {{ request.user.student.xp }}
    </div>
{% endif %}
    <div>
        <form action="{% url 'user:delete_account' %}" method="post">
            {% csrf_token %}
            <a href="{% url 'user:change_password' %}" class="btn btn-primary m-3">Change password</a>
            <button class="btn btn-primary m-3" type="submit"onclick="return confirm('Are you sure? This will delete all data associated with your account.');">Delete account</button>
        </form>
    </div>
    
</div>
{% endblock %}

user/templates/user/register.html
{% extends 'core/base.html' %}

{% block content %}
<div>
    <h1>Signup</h1>

    <form method="post" action=".">
        {% csrf_token %}

        <div class="mb-3">
            <label class="inline-block mb-2">Username:</label><br>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Email:</label><br>
            {{ form.email }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Password:</label><br>
            {{ form.password1 }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Repeat password:</label><br>
            {{ form.password2 }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Role:</label><br>
            {{ form.role }}
        </div>

        {% if form.errors or form.non_field_errors %}
        {% for field in form %}
            {% for error in field.errors %}
                <p style="color: red">{{ error }}</p>
            {% endfor %}
        {% endfor %}
        {% endif %}
        <button class="btn btn-primary">Submit</button>
    </form>
</div>
{% endblock %}