classroom/urls.py
from django.urls import path

from . import views

app_name = 'classroom'

urlpatterns = [
    path('', views.index, name='index'),
    path('student/', views.student, name='student'),
    path('teacher/', views.teacher, name='teacher'),
    path('teacher/newClassroom/', views.newClassroom, name='newClassroom'),
    path('teacher/<int:classroom_id>/', views.teacherClassroom, name='teacherClassroom'),
    path('teacher/editStudent/<int:student_id>/', views.editStudent, name='editStudent'),
    path('teacher/resetStudent/<int:student_id>/', views.resetStudent, name='resetStudent'),
    path('teacher/removeStudent/<int:student_id>/', views.removeStudent, name='removeStudent'),
    path('student/<int:classroom_id>/', views.studentClassroom, name='studentClassroom'),
    path('teacher/<int:classroom_id>/newLesson/', views.newLesson, name='newLesson'),
    path('teacher/<int:classroom_id>/editLesson/<int:lesson_id>/', views.editLesson, name='editLesson'),
    path('teacher/<int:classroom_id>/deleteLesson/<int:lesson_id>/', views.deleteLesson, name='deleteLesson'),
    path('student/<int:classroom_id>/lesson/<int:lesson_id>/', views.viewLesson, name='viewLesson'),
    path('student/<int:classroom_id>/lesson/<int:lesson_id>/survey/', views.survey, name='survey'),
    path('teacher/<int:classroom_id>/lesson/<int:lesson_id>/survey/results', views.surveyResults, name='surveyResults'),
    path('teacher/<int:classroom_id>/previewLesson/<int:lesson_id>/', views.previewLesson, name='previewLesson'),
    path('teacher/<int:classroom_id>/lesson/<int:lesson_id>/newQuiz/', views.newQuiz, name='newQuiz'),
    path('teacher/<int:classroom_id>/lesson/<int:lesson_id>/editQuiz/', views.editQuiz, name='editQuiz'),
    path('teacher/<int:classroom_id>/lesson/<int:lesson_id>/editQuiz/question/<int:question_id>/edit/', views.editQuizQuestion, name='editQuizQuestion'),
    path('teacher/<int:classroom_id>/lesson/<int:lesson_id>/editQuiz/question/<int:question_id>/delete/', views.deleteQuizQuestion, name='deleteQuizQuestion'),
    path('teacher/<int:classroom_id>/lesson/<int:lesson_id>/editQuiz/question/add/', views.addQuizQuestion, name='addQuizQuestion'),
    path('student/<int:classroom_id>/lesson/<int:lesson_id>/quiz/', views.takeQuiz, name='takeQuiz'),
    path('student/<int:classroom_id>/lesson/<int:lesson_id>/quiz/results', views.viewQuizResults, name='viewQuizResults'),
    path('teacher/<int:classroom_id>/student/detail/<int:student_id>/', views.studentDetail, name='studentDetail'),
]

core/urls.py
from django.urls import path

from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('buy/', views.buy, name='buy'),
    path('sell/', views.sell, name='sell'),
    path('quote/', views.quote, name='quote'),
    path('history/', views.history, name='history'),
    path('leaderboard/', views.leaderboard, name='leaderboard'),
]

educaitonalStockTracker/urls.py
from django.contrib import admin
from django.urls import path, include # new
from django.conf import settings # new
from django.conf.urls.static import static # new

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')), # new
    path('', include('core.urls')), # new
    path('__debug__/', include('debug_toolbar.urls')), # new
    path('classroom/', include('classroom.urls')), # new
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views
from .forms import LoginForm

app_name = 'user'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='user/login.html', authentication_form=LoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password/', views.CustomPasswordChangeView.as_view(template_name='user/change_password.html', success_url='/'), name='change_password'),
    path('profile/', views.profile, name='profile'),
    path('delete/', views.deleteAccount, name='delete_account')
]

core/models.py
from django.db import models

from user.models import Student

# Create your models here.
class Transactions(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    symbol = models.CharField(max_length=10)
    quantity = models.IntegerField()
    purchase_price = models.DecimalField(max_digits=10, decimal_places=2)
    date = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        verbose_name_plural = "Transactions"
        ordering = ['-date']

    def __str__(self):
        return self.symbol
    
class Holdings(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    symbol = models.CharField(max_length=10)
    quantity = models.IntegerField()
    purchase_price = models.DecimalField(max_digits=10, decimal_places=2)
    
    class Meta:
        verbose_name_plural = "Holdings"
        ordering = ['symbol']
    
    def __str__(self):
        return f'{self.quantity} | {self.symbol} (${self.purchase_price}) | {self.student}'

core/forms.py
from django import forms
from django.core.validators import MinValueValidator

from .models import Holdings

class QuoteForm(forms.Form):
    symbol = forms.CharField(max_length=10, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Symbol',
        'autofocus': 'autofocus',
        }))
    
class BuyForm(forms.Form):
    symbol = forms.CharField(max_length=10, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Symbol',
        'autofocus': 'autofocus',
        }))
    shares = forms.IntegerField(
        validators=[MinValueValidator(1)],
        widget=forms.NumberInput(attrs={
        'class': 'form-control',
        'placeholder': 'Number of shares',
        }))
    
class SellForm(forms.Form):
    holding = forms.ModelChoiceField(queryset=None, widget=forms.Select(attrs={
        'class': 'form-control',
        'placeholder': 'Holding',
        'autofocus': 'autofocus',
        }))
    quantity = forms.IntegerField(widget=forms.NumberInput(attrs={
        'class': 'form-control',
        'placeholder': 'Number of shares',
        }))
    
    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request')
        super(SellForm, self).__init__(*args, **kwargs)
        self.fields['holding'].queryset = Holdings.objects.filter(student__user=self.request.user)


        
        

core/views.py
from django.shortcuts import render,redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db.models import F, Sum

from django.core.cache import cache

from .utils import lookup, eightNextDay
from user.decorators import allowed_users, passwordAgeCheck
from .forms import QuoteForm, BuyForm, SellForm
from .models import Transactions, Holdings
from user.models import Student

import decimal

# Create your views here.

@login_required
@passwordAgeCheck()
def index(request):
    # redirect teachers to the classroom page
    if request.user.role == 'TEACHER':
        return redirect('classroom:teacher')
    if request.method == 'POST':
        # Get the student object.
        student = get_object_or_404(Student, user=request.user)
        # get the holdings of the student and group the holdings by symbol and purchase price
        holdings = Holdings.objects.filter(student=student).values('symbol', 'purchase_price').annotate(quantity=Sum('quantity'))

        
        stocks = []
        for holding in holdings:
            # check if holding is in cache
            # caching the price prevents repeat api calls, significantly improving performance
            if cache.get(holding['symbol']):
                price = cache.get(holding['symbol'])
            else:
                # Call lookup function from utils.py, the api call is made here.
                price = lookup(holding['symbol'])
                # Check if the api call was successful.
                if price == "API LIMIT":
                    messages.error(request, 'API LIMIT.')
                    return redirect('core:index')
                elif price == "INVALID SYMBOL":
                    messages.error(request, 'Invalid symbol.')
                    return redirect('core:index')
                
                # add price to cache, setting to timeout at 8am the next day
                cache.set(holding['symbol'], price, timeout=eightNextDay())
            

            
                
            
            # Calculate the total value of the stock.
            totalValue = price * decimal.Decimal(holding['quantity'])
            totalPurchasePrice = holding['purchase_price'] * (holding['quantity'])
            # Calculate the profit/loss of the stock.
            profitLoss = totalValue - totalPurchasePrice
            
            # Add the stock to the list.
            stocks.append({
                'symbol': holding['symbol'],
                'total_quantity': holding['quantity'],
                'purchase_price': holding['purchase_price'],
                'price': price,
                'totalValue': totalValue,
                'profitLoss': profitLoss,
                })
        
        # Calculate the total value of the student's portfolio.
        totalValue = sum([stock['totalValue'] for stock in stocks])

        if stocks:
            student.total_value = totalValue + student.cash
            student.save()
        return render(request, 'core/index.html', {'stocks': stocks})

    return render(request, 'core/index.html')

@login_required
@allowed_users(allowed_roles=['STUDENT'])
def buy(request):
    if request.method == 'POST':
        form = BuyForm(request.POST)
        if form.is_valid():
            symbol = form.cleaned_data['symbol'].upper()
            shares = form.cleaned_data['shares']
            
            if cache.get(symbol):
                price = cache.get(symbol)
            else:
                # Call lookup function from utils.py, the api call is made here.
                price = lookup(symbol)
                # Check if the api call was successful.
                if price == "API LIMIT":
                    messages.error(request, 'API LIMIT.')
                    return redirect('core:buy')
                elif price == "INVALID SYMBOL":
                    messages.error(request, 'Invalid symbol.')
                    return redirect('core:buy')
                
                # add price to cache, setting to timeout at 8am the next day
                cache.set(symbol, price, timeout=eightNextDay())

            

            totalCost = price * decimal.Decimal(shares)
            
            # Get the student object.
            student = get_object_or_404(Student, user=request.user)

            # Check if the student has enough balance to make the purchase.
            if student.cash < totalCost:
                messages.error(request, 'Insufficient funds.')
                return redirect('core:buy')
            
            # Update the student's balance.
            # F is used to prevent race conditions.
            student.cash = F("cash") - totalCost
            student.save()

            # Create a transaction object.
            transaction = Transactions(student=student, symbol=symbol, quantity=shares, purchase_price=price)
            transaction.save()

            # check if the student already has a holding for this stock at this price point
            if Holdings.objects.filter(student=student, symbol=symbol, purchase_price=price).exists():
                # if so, update the holding
                holding = Holdings.objects.get(student=student, symbol=symbol, purchase_price=price)
                holding.quantity = F("quantity") + shares
                holding.save()
            else:
                holding = Holdings(student=student, symbol=symbol, purchase_price=price, quantity=shares)
                holding.save()
            
            messages.success(request, 'Successful transaction! %s %s share(s) at $%s per share.' % (shares, symbol, price))
            return redirect('core:index')
        else:
            return render(request, 'core/buy.html', {'form': form})

    form = BuyForm()
    return render(request, 'core/buy.html', {'form': form})

@login_required
@allowed_users(allowed_roles=['STUDENT'])
def sell(request):
    if request.method == 'POST':
        form = SellForm(request.POST, request=request)
        if form.is_valid():
            
            # Get the holding object.
            holding = form.cleaned_data['holding']
            quantity = form.cleaned_data['quantity']

            # Get the symbol of the stock.
            symbol = holding.symbol
            # Get the student object.
            student = get_object_or_404(Student, user=request.user)

            # Check if the student has enough shares to sell.
            if holding.quantity < quantity:
                messages.error(request, 'Insufficient shares.')
                return redirect('core:sell')
            
            # Update the holding object.
            if quantity == holding.quantity:
                holding.delete()
            else:
                holding.quantity = F("quantity") - quantity
                holding.save()

            if cache.get(symbol):
                price = cache.get(symbol)
            else:
                # Call lookup function from utils.py, the api call is made here.
                price = lookup(symbol)
                # Check if the api call was successful.
                if price == "API LIMIT":
                    messages.error(request, 'API LIMIT.')
                    return redirect('core:buy')
                elif price == "INVALID SYMBOL":
                    messages.error(request, 'Invalid symbol.')
                    return redirect('core:buy')
                
                # add price to cache, setting to timeout at 8am the next day
                cache.set(holding['symbol'], price, timeout=eightNextDay())

            # calculate the profit of the sale
            profit = int((price - holding.purchase_price) * decimal.Decimal(quantity))
            # increase the students xp by 10% of the profit but cap the increase at 50
            student.xpUp(min(50, int(profit * 0.1)))
            # Update the student's balance. F is used to prevent race conditions.
            student.cash = F("cash") + (price * decimal.Decimal(quantity))
            student.save()

            # Create a transaction a new transaction for this sale.
            transaction = Transactions(student=student, symbol=symbol, quantity=-quantity, purchase_price=price)
            transaction.save()

            messages.success(request, 'Successful transaction! Sold %s %s share(s) at $%s per share. For a profit/loss of $%s!' % (quantity, symbol, price, price - holding.purchase_price))

            return redirect('core:index')
    form = SellForm(request=request)
    return render(request, 'core/sell.html', {
        'form': form
        })

@login_required
@allowed_users(allowed_roles=['STUDENT'])
def quote(request):
    if request.method == 'POST':
        form = QuoteForm(request.POST)
        if form.is_valid():
            symbol = form.cleaned_data['symbol'].upper()

            if cache.get(symbol):
                price = cache.get(symbol)
            else:
                # Call lookup function from utils.py, the api call is made here.
                price = lookup(symbol)
                # Check if the api call was successful.
                if price == "API LIMIT":
                    messages.error(request, 'API LIMIT.')
                    return redirect('core:quote')
                elif price == "INVALID SYMBOL":
                    messages.error(request, 'Invalid symbol.')
                    return redirect('core:quote')
                
                # add price to cache, setting to timeout at 8am the next day
                cache.set(symbol, price, timeout=eightNextDay())

                

        symbol = symbol.upper()
        return render(request, 'core/price.html', {
        'symbol': symbol,
        'price': price
        })
    
    preSymbol = request.GET.get('symbol', '')
    form = QuoteForm()
    
    return render(request, 'core/quote.html', {
        'form': form,
        'preSymbol': preSymbol,
        })

@login_required

core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="{% block description %}{% endblock %}">
    <meta name="keywords" content="{% block keywords %}{% endblock %}">
    <meta name="author" content="Jordan Dovey">
    
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <!-- Intro.JS -->
    <script src="https://cdn.jsdelivr.net/npm/intro.js@7.2.0/intro.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/intro.js@7.2.0/minified/introjs.min.css" rel="stylesheet">


    <!-- Google Fonts -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />

    {% load static %}
    <link rel="stylesheet" href="{% static 'core/style.css' %}">
    <link rel="icon" type="image/x-icon" href="{% static 'core/favicon.ico' %}">
    <title>{% block title %}{% endblock %} | Educational Stock Tracker</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light border">
        <a href="{% url 'core:index' %}" class="navbar-brand">Educational Stock Tracker</a>
        <button aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler" data-target="#navbar" data-toggle="collapse" type="button">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbar">
            {% if request.user.is_authenticated %}
            <ul class="navbar-nav mr-auto mt-2">
                {% if request.user.role == 'STUDENT' %}
                <li class="nav-item">
                    <a href="{% url 'core:buy' %}" class="nav-link">Buy</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'core:sell' %}" class="nav-link">Sell</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'core:quote' %}" class="nav-link">Quote</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'core:history' %}" class="nav-link">History</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'core:leaderboard' %}" class="nav-link">Leaderboard</a>
                </li>
            {% endif %}
                <li class="nav-item">
                    <a href="{% url 'classroom:index' %}" class="nav-link">Classroom</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'user:logout' %}" class="nav-link">Logout</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'user:profile' %}" class="nav-link">Profile</a>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link" id="start-steps">Page tour</a>
                </li>
            </ul>
            {% else %}
            <ul class="navbar-nav mr-auto mt-2">
                <li class="nav-item">
                    <a href="{% url 'user:login' %}" class="nav-link">Login</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'user:register' %}" class="nav-link">Register</a>
                </li>
            </ul>
            {% endif %}
            {% if request.user.role == 'STUDENT' %}
            {% load custom_filters %}
            <div class="w-50 d-flex justify-content-md-end justify-content-sm-start">
                <div class="progress w-50" title="Level: {{request.user.student.xp|div:100}} | {{ request.user.student.xp|mod:100 }}/100xp" id="experience-bar">
                    <div class="progress-bar" role="progressbar" style="width: {{ request.user.student.xp|mod:100 }}%;" aria-valuenow="{{ request.user.student.xp|mod:100 }}" aria-valuemin="0" aria-valuemax="100">
                        <small class="progress-label justify-content-center d-flex position-absolute w-100 text-dark">Level: {{request.user.student.xp|div:100}} | {{ request.user.student.xp|mod:100 }}/100xp</small>
                    </div>
                </div>
            </div>
            {% endif %}
        </div>
    </nav>

    <header>
        {% for msg in messages %}
        {% if msg.tags == 'error' %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
        {% else %}
        <div class="alert alert-success alert-dismissible fade show" role="alert">
        {% endif %}
            <strong>Alert!</strong> {{ msg }}
        </div>
    </header>
        
    {% endfor %}
    <main class="container p-5">
        <script src="{% static 'core/script.js' %}"></script>
        {% block content %}
        {% endblock %}
    </main>

    <footer class="small text-center text-muted">
        Data provided for free by <a href="https://www.alphavantage.co/">Alpha-Vantage</a>. View <a href="https://www.alphavantage.co/terms_of_service/">Alpha-Vantage's Terms of Use</a>.
    </footer>
</footer>
</body>
</html>

core/templates/core/buy.html
{% extends 'core/base.html' %}

{% block title %}Buy{% endblock %}
    
{% block content %}
<div>
    <form action="." method="post">
        <div class="form-group"></div>
        {% csrf_token %}
        {{ form.symbol }}
        {{ form.shares }}

        <!-- Display any form errors -->
        {% for field in form %}
            {% for error in field.errors %}
                <p style="color: red">{{ error }}</p>
            {% endfor %}
        {% endfor %}
        </div>
        <button class="m-3 btn btn-primary" type="submit">Buy</button>
    </form>
</div>
{% endblock %}

core/templates/core/history.html
{% extends 'core/base.html' %}

{% block title %}History{% endblock %}
    
{% block content %}
    <h1>History</h1>
    <table class="table table-striped table-dark table-hover styled-table">
        <thead>
            <tr>
                <th>Symbol</th>
                <th>Shares</th>
                <th>Price @ Purchase</th>
                <th>Date</th>
            </tr>
        </thead>
        <tbody class="">
            {% for transaction in transactions %}
            <tr>
                <!-- create a td of the transaction symbol that will link to the quote page, passing the symbol-->
                <td><a href="{% url 'core:quote' %}?symbol={{ transaction.symbol }}">{{ transaction.symbol }}</a></td>
                <td>{{ transaction.quantity }}</td>
                <td>${{ transaction.purchase_price }}</td>
                <td>{{ transaction.date }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}
    

core/templates/core/index.html
{% extends 'core/base.html' %}

{% block title %}Dashboard{% endblock %}
    
{% block content %}
    <!-- button that sends a post request to index so the dashboard will show-->
    {% if request.user.role == 'STUDENT' %}
    <form action="{% url 'core:index' %}" method="post">
        {% csrf_token %}
        <button class="btn btn-primary btn-lg m-2" type="submit">View Dashboard</button>
    </form>
    <div class="table-responsive">
    <table class="table table-striped table-dark table-hover styled-table" id="holdings-table">
        <thead>
            <tr>
                <th>Symbol</th>
                <th>Shares</th>
                <th>Purchase Price</th>
                <th>Current Price</th>
                <th>Value of Holding</th>
                <th>Profit/Loss</th>
            </tr>
        </thead>
        <tbody>
            {% for stock in stocks %}
            <tr>
                <td>{{ stock.symbol }}</td>
                <td>{{ stock.total_quantity }}</td>
                <td>${{ stock.purchase_price }}</td>
                <td>${{ stock.price }}</td>
                <td>${{ stock.totalValue }}</td>
                <td>${{ stock.profitLoss }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    </div>

    <table class="table table-striped table-dark table-hover styled-table" id="personal-table">
        <thead>
            <tr>
                <th>Cash</th>
                <th>Overall Balance</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>${{ request.user.student.cash }}</td>
                <td>${{ request.user.student.total_value }}</td>
            </tr>
        </tbody>
    </table>
    {% endif %}

    <script>
        intro.setOptions({
            steps: [
                {
                    element: '#navbar',
                    intro: 'This is the navbar. It contains links to all the pages you can visit.',
                },
                {
                    element: '#experience-bar',
                    intro: 'This is your experience bar. You gain experience by completing lessons and quizzes and through trades. When you gain enough experience, you will level up.',
                },
                {
                    element: '#holdings-table',
                    intro: 'This table shows your current holdings. You can click on the button to expand it.',
                    position: 'top'
                },
                {
                    element: '#personal-table',
                    intro: 'This table shows your current cash and overall balance.',
                    position: 'top'
                }
            ]
        })
    </script>

{% endblock %}
    

core/templates/core/leaderboard.html
{% extends 'core/base.html' %}

{% block title %}Leaderboard{% endblock %}
    
{% block content %}
    <h1>Leaderboard</h1>
    <table class="table table-striped table-dark table-hover styled-table">
        <thead>
            <tr>
                <th>Username</th>
                <th>Overall Balance</th>
                <th>XP</th>
            </tr>
        </thead>
        <tbody>
            {% for student in students %}
            {% if student.user.username == request.user.username %}
            <tr class="active-row">
            {% else %}
            <tr>
            {% endif %}
                <td>{{ student.user.username }}</td>
                <td>${{ student.total_value }}</td>
                <td>{{ student.xp }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}
    

core/templates/core/price.html
{% extends 'core/base.html' %}

{% block title %}Price{% endblock %}
    
{% block content %}
    <div class="form-group">
        {% if price %}
            <h1>{{ symbol }}: is ${{ price }}</h1>
        {% else %}
            <h1>Symbol not found</h1>
        {% endif %}

        <button class="m-3 btn btn-primary" onclick="window.history.back();">Back</button>
    </div>
{% endblock %}

core/templates/core/quote.html
{% extends 'core/base.html' %}

{% block title %}Quote{% endblock %}
    
{% block content %}
    <div>
        <form action="." method="post">
            <div class="form-group"></div>
            {% csrf_token %}
            
            {% if preSymbol %}
                <input class="form-control" type="text" name="symbol" value="{{ preSymbol }}" required>
            {% else %}
                {{ form.symbol }}    
            {% endif %}
            

            <!-- Display any form errors -->
            {% for field in form %}
                {% for error in field.errors %}
                    <p style="color: red">{{ error }}</p>
                {% endfor %}
            {% endfor %}
            </div>

            
            
            {% if preSymbol %}
            <button class="m-3 btn btn-primary" type="submit" autofocus="autofocus">Quote</button>
            {% else %}
            <button class="m-3 btn btn-primary" type="submit">Quote</button>
            {% endif %}

        </form>
    </div>

{% endblock %}

core/templates/core/sell.html
{% extends 'core/base.html' %}

{% block title %}Sell{% endblock %}
    
{% block content %}
<div>
    <form action="." method="post">
        <div class="form-group"></div>
            {% csrf_token %}
            {{ form.as_p }}
            <!-- Display any form errors -->
            {% for field in form %}
                {% for error in field.errors %}
                    <p style="color: red">{{ error }}</p>
                {% endfor %}
            {% endfor %}
        </div>
        <button class="m-3 btn btn-primary" type="submit">Sell</button>
    </form>
</div>
{% endblock %}