classroom/urls.py
from django.urls import path

from . import views

app_name = 'classroom'

urlpatterns = [
    path('', views.index, name='index'),
    path('student/', views.student, name='student'),
    path('teacher/', views.teacher, name='teacher'),
    path('teacher/newClassroom/', views.newClassroom, name='newClassroom'),
    path('teacher/<int:classroom_id>/', views.teacherClassroom, name='teacherClassroom'),
    path('teacher/editStudent/<int:student_id>/', views.editStudent, name='editStudent'),
    path('teacher/resetStudent/<int:student_id>/', views.resetStudent, name='resetStudent'),
    path('teacher/removeStudent/<int:student_id>/', views.removeStudent, name='removeStudent'),
    path('student/<int:classroom_id>/', views.studentClassroom, name='studentClassroom'),
    path('teacher/<int:classroom_id>/newLesson/', views.newLesson, name='newLesson'),
    path('teacher/<int:classroom_id>/editLesson/<int:lesson_id>/', views.editLesson, name='editLesson'),
    path('teacher/<int:classroom_id>/deleteLesson/<int:lesson_id>/', views.deleteLesson, name='deleteLesson'),
    path('student/<int:classroom_id>/lesson/<int:lesson_id>/', views.viewLesson, name='viewLesson'),
    path('student/<int:classroom_id>/lesson/<int:lesson_id>/survey/', views.survey, name='survey'),
    path('teacher/<int:classroom_id>/lesson/<int:lesson_id>/survey/results', views.surveyResults, name='surveyResults'),
    path('teacher/<int:classroom_id>/previewLesson/<int:lesson_id>/', views.previewLesson, name='previewLesson'),
    path('teacher/<int:classroom_id>/lesson/<int:lesson_id>/newQuiz/', views.newQuiz, name='newQuiz'),
    path('teacher/<int:classroom_id>/lesson/<int:lesson_id>/editQuiz/', views.editQuiz, name='editQuiz'),
    path('teacher/<int:classroom_id>/lesson/<int:lesson_id>/editQuiz/question/<int:question_id>/edit/', views.editQuizQuestion, name='editQuizQuestion'),
    path('teacher/<int:classroom_id>/lesson/<int:lesson_id>/editQuiz/question/<int:question_id>/delete/', views.deleteQuizQuestion, name='deleteQuizQuestion'),
    path('teacher/<int:classroom_id>/lesson/<int:lesson_id>/editQuiz/question/add/', views.addQuizQuestion, name='addQuizQuestion'),
    path('student/<int:classroom_id>/lesson/<int:lesson_id>/quiz/', views.takeQuiz, name='takeQuiz'),
    path('student/<int:classroom_id>/lesson/<int:lesson_id>/quiz/results', views.viewQuizResults, name='viewQuizResults'),
    path('teacher/<int:classroom_id>/student/detail/<int:student_id>/', views.studentDetail, name='studentDetail'),
]

core/urls.py
from django.urls import path

from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('buy/', views.buy, name='buy'),
    path('sell/', views.sell, name='sell'),
    path('quote/', views.quote, name='quote'),
    path('history/', views.history, name='history'),
    path('leaderboard/', views.leaderboard, name='leaderboard'),
]

educaitonalStockTracker/urls.py
from django.contrib import admin
from django.urls import path, include # new
from django.conf import settings # new
from django.conf.urls.static import static # new

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')), # new
    path('', include('core.urls')), # new
    path('__debug__/', include('debug_toolbar.urls')), # new
    path('classroom/', include('classroom.urls')), # new
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

classroom/models.py
from django.db import models
from django.contrib.postgres.fields import ArrayField

# Create your models here.

class Classroom(models.Model):
    name = models.CharField(max_length=100, unique=True)
    passcode = models.CharField(max_length=100)
    teacher = models.ForeignKey('user.Teacher', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.name
    
class Lesson(models.Model):
    class Status(models.TextChoices):
        DRAFT = 'DRAFT', 'draft'
        PUBLISHED = 'PUBLISHED', 'published'
        
    class Meta:
        unique_together = ('order', 'classroom')
        
    base_status = Status.DRAFT
    
    status = models.CharField(max_length=50, choices=Status.choices, default=base_status)
    order = models.PositiveIntegerField(default = 0, blank = False, null = False)
    classroom = models.ForeignKey('classroom.Classroom', on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=256)
    image = models.ImageField(upload_to='uploaded_images', blank=True, null=True)
    lesson_outline = models.JSONField(blank=True, null=True)
    
    def __str__(self):
        return self.title

class SurveyResponse(models.Model):
    class Meta:
        unique_together = ('lesson', 'student')
    
    lesson = models.ForeignKey('classroom.Lesson', on_delete=models.CASCADE)
    student = models.ForeignKey('user.Student', on_delete=models.CASCADE)
    content_understanding = models.IntegerField(choices=[
        (1, 'Very well'),
        (2, 'Somewhat well'),
        (3, 'Not well')
    ])
    
    engagement = models.IntegerField(choices=[
        (1, 'Very engaged'),
        (2, 'Moderately engaged'),
        (3, 'Not very engaged')
    ])
    
    assessment_accuracy = models.BooleanField()
    
    satisfaction = models.IntegerField(choices=[
        (1, 'Not satisfied at all'),
        (2, '2'),
        (3, '3'),
        (4, '4'),
        (5, 'Very satisfied')
    ])
    
    improvement_suggestions = models.TextField(blank=True, null=True)
    
    def __str__(self):
        return self.lesson.title + ' - ' + self.student.user.username
    
class QuizQuestion(models.Model):
    class Meta:
        unique_together = ('lesson', 'order')
        
    lesson = models.ForeignKey('classroom.Lesson', on_delete=models.CASCADE)
    question = models.CharField(max_length=100)
    order = models.PositiveIntegerField(default = 0, blank = False, null = False)
    answer = models.CharField(max_length=100)
    op1 = models.CharField(max_length=100)
    op2 = models.CharField(max_length=100)
    op3 = models.CharField(max_length=100)
    
    def __str__(self):
        return self.question + ' - ' + self.lesson.title

class QuizResponse(models.Model):
    class Meta:
        unique_together = ('question', 'student')
    
    question = models.ForeignKey('classroom.QuizQuestion', on_delete=models.CASCADE)
    student = models.ForeignKey('user.Student', on_delete=models.CASCADE)
    answer = models.CharField(max_length=100)
    
    def __str__(self):
        return self.question.question + ' - ' + self.answer + ' - ' + self.student.user.username
    
class LessonQuizScore(models.Model):
    class Meta:
        unique_together = ('lesson', 'student')
        
    lesson = models.ForeignKey('classroom.Lesson', on_delete=models.CASCADE)
    student = models.ForeignKey('user.Student', on_delete=models.CASCADE)
    score = models.IntegerField()
    
class CommentMessage(models.Model):
    lesson = models.ForeignKey('classroom.Lesson', on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey('user.User', on_delete=models.CASCADE)
    
    class Meta:
        ordering = ['created_at']
        
    def __str__(self):
        return self.content + ' - ' + self.created_by.username + ' - ' + self.lesson.title

classroom/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.forms import formset_factory
from django.db.models import F

from user.models import Student
from .models import Classroom, Lesson, SurveyResponse, QuizQuestion, QuizResponse, LessonQuizScore, CommentMessage
from user.decorators import allowed_users
from core.models import Holdings
from .forms import NewClassroomForm, JoinClassroomForm, EditStudentForm, LessonForm, LearningObjectiveFormSet, SurveyResponseForm, QuizQuestionFormSet, QuizQuestionForm, QuizResponseForm, QuizResponseFormSetBase, CommentMessageForm
import json
import statistics

# Create your views here.

@login_required
@allowed_users(allowed_roles=['STUDENT', 'TEACHER'])
def index(request):
    if request.user.role == 'STUDENT':
        return redirect('classroom:student')
    elif request.user.role == 'TEACHER':
        return redirect('classroom:teacher')
    return render(request, 'classroom/index.html')

@login_required
@allowed_users(allowed_roles=['STUDENT'])
def student(request):
    if request.user.student.classroom:
        return redirect('classroom:studentClassroom', classroom_id=request.user.student.classroom.id)
    if request.method == 'POST':
        form = JoinClassroomForm(request.POST)
        if form.is_valid():
            
            try:
                classroom = Classroom.objects.get(name=form.cleaned_data['name'])
            except Classroom.DoesNotExist:
                messages.error(request, 'The classroom you entered does not exist.')
                return redirect('classroom:student')
            
            passcode = form.cleaned_data['passcode']
            if classroom.passcode == passcode:
                student = request.user.student
                student.classroom = classroom
                student.save()
                successMessage = "You have successfully joined %s's classroom." % classroom.teacher.user.username
                messages.success(request, successMessage)
                
                return redirect('classroom:studentClassroom', classroom_id=classroom.id)
            else:
                messages.error(request, 'The passcode you entered is incorrect.')
                return redirect('classroom:student')
    form = JoinClassroomForm()
    return render(request, 'classroom/student.html', {
        'form': form
        })

@login_required
@allowed_users(allowed_roles=['TEACHER'])
def teacher(request):
    # get the classrooms of the teacher
    teacher_classrooms = Classroom.objects.filter(teacher=request.user.teacher)
    return render(request, 'classroom/teacher.html', {'teacher_classrooms': teacher_classrooms})

@login_required
@allowed_users(allowed_roles=['TEACHER'])
def newClassroom(request):
    if request.method == 'POST':
        form = NewClassroomForm(request.POST)
        if form.is_valid():
            # save the classroom without committing to the database
            classroom = form.save(commit=False)
            # this allows us to add the teacher to the classroom
            classroom.teacher = request.user.teacher
            classroom.save()
            
            return redirect('classroom:teacherClassroom', classroom_id=classroom.id)
        else:
            return render(request, 'classroom/newClassroom.html', {
                'form': form,
            })
            
    form = NewClassroomForm()
    return render(request, 'classroom/newClassroom.html', {
        'form': form,
        })

@login_required
@allowed_users(allowed_roles=['TEACHER'])
def teacherClassroom(request, classroom_id):
    classroom = Classroom.objects.get(id=classroom_id)
    # check if the classroom belongs to the teacher
    if classroom.teacher != request.user.teacher:
        messages.error(request, 'You do not have permission to view this classroom.')
        return redirect('classroom:teacher')
    classroomStudents = Student.objects.filter(classroom=classroom).order_by('-total_value')
    # get the lessons in the classroom order by their order
    classroomLessons = Lesson.objects.filter(classroom=classroom).order_by('order')
    
    for lesson in classroomLessons:
        # check if there is an associated quiz
        lesson.has_quiz = QuizQuestion.objects.filter(lesson=lesson).exists()
        # get count of students who have completed the survey
        lesson.survey_responses = SurveyResponse.objects.filter(lesson=lesson).count()
        # get count of students who have completed the quiz
        lesson.quiz_responses = QuizResponse.objects.filter(question__lesson=lesson).values('student').distinct().count()
        # get the average score of the students who have completed the quiz
        # first get the score value of the students who have completed the quiz
        studentScores = LessonQuizScore.objects.filter(lesson=lesson).values_list('score', flat=True)
        # if there are no scores, set the average to 0
        if not studentScores:
            lesson.average = "Not taken yet"
        else:
            # then get the average of the scores and add to lesson
            lesson.average = statistics.mean(studentScores)
        
    return render(request, 'classroom/teacherClassroom.html', {
        'classroom': classroom,
        'classroomStudents': classroomStudents,
        'classroomLessons': classroomLessons,
        })
    
@login_required
@allowed_users(allowed_roles=['STUDENT'])
def studentClassroom(request, classroom_id):
    classroom = Classroom.objects.get(id=classroom_id)
    # check if the classroom belongs to the student
    if classroom != request.user.student.classroom:
        messages.error(request, 'You do not have permission to view this classroom.')
        return redirect('classroom:student')
    # get the students in the classroom order by their total_value
    classroomStudents = Student.objects.filter(classroom=classroom).order_by('-total_value')
    # get the published lessons in the classroom order by their order
    classroomLessons = Lesson.objects.filter(classroom=classroom, status='PUBLISHED').order_by('order')
    
    # for each lesson, check if the student has completed the survey and quiz
    for lesson in classroomLessons:
        if SurveyResponse.objects.filter(lesson=lesson, student=request.user.student).exists():
            lesson.completed_survey = True
        if QuizResponse.objects.filter(question__lesson=lesson, student=request.user.student).exists():
            lesson.completed_quiz = True
                 
    return render(request, 'classroom/studentClassroom.html', {
        'classroom': classroom,
        'classroomStudents': classroomStudents,
        'classroomLessons': classroomLessons,
        })
    
@login_required
@allowed_users(allowed_roles=['TEACHER'])
def editStudent(request, student_id):
    student = Student.objects.get(user_id=student_id)
    if student.classroom.teacher != request.user.teacher:
        messages.error(request, 'You do not have permission to edit this student.')
        return redirect('classroom:teacher')
    
    if request.method == 'POST':
        form = EditStudentForm(request.POST, instance=student)
        if form.is_valid():
            form.save()
            return redirect('classroom:teacherClassroom', classroom_id=student.classroom.id)
    form = EditStudentForm(instance=student)
    return render(request, 'classroom/editStudent.html', {
        'form': form,
        'student': student,
        })
    
@login_required
@allowed_users(allowed_roles=['TEACHER'])
def resetStudent(request, student_id):
    student = Student.objects.get(user_id=student_id)
    if student.classroom.teacher != request.user.teacher:
        messages.error(request, 'You do not have permission to remove this student.')
        return redirect('classroom:teacher')
    # reset student values
    student.cash = 10000.00
    student.total_value = 10000.00
    student.save()
    # delete their holdings
    Holdings.objects.filter(student=student).delete()
    return redirect('classroom:teacherClassroom', classroom_id=student.classroom.id)

@login_required
@allowed_users(allowed_roles=['TEACHER'])
def removeStudent(request, student_id):
    student = Student.objects.get(user_id=student_id)
    classroom_id = student.classroom.id
    if student.classroom.teacher != request.user.teacher:
        messages.error(request, 'You do not have permission to remove this student.')
        return redirect('classroom:teacher')
    
    
    student.classroom = None
    student.save()
    messages.success(request, 'You have successfully removed %s from your classroom.' % student.user.username)
    return redirect('classroom:teacherClassroom', classroom_id)
    
@login_required
@allowed_users(allowed_roles=['TEACHER'])
def newLesson(request, classroom_id):
    classroom = Classroom.objects.get(id=classroom_id)
    if request.method == 'POST':
        form = LessonForm(request.POST, request.FILES)
        objective_forms = LearningObjectiveFormSet(request.POST, prefix=0)
        if form.is_valid() and all(form.is_valid() for form in objective_forms):
            # check if the order and classroom combination already exists
            if Lesson.objects.filter(order=form.cleaned_data['order'], classroom=Classroom.objects.get(id=classroom_id)).exists():
                messages.error(request, 'A lesson with that order already exists.')
            else:
                # save the lesson without committing to the database
                lesson = form.save(commit=False)
                # this allows us to add the teacher and the learning outline to the lesson
                lesson.teacher = request.user.teacher
                lesson.classroom = classroom
                
                
                learning_objectives = []
                for objective_form in objective_forms:
                    objective_text = objective_form.cleaned_data['learning_objective']

classroom/templates/classroom/editLesson.html
{% extends 'classroom/lessonForm.html' %}

{% block button %}
    <button class="m-3 btn btn-primary" type="submit">Submit</button>
{% endblock %}

classroom/templates/classroom/editQuizQuestion.html
{% extends 'core/base.html' %}

{% block title %}Classroom{% endblock %}
    
{% block content %}

    <div>
        <form action="." method="post">
            <div class="form-group"></div>
                {% csrf_token %}
                {{form.as_p}}
                <!-- Display any form errors -->
                {% for field in form %}
                    {% for error in field.errors %}
                        <p style="color: red">{{ error }}</p>
                    {% endfor %}
                {% endfor %}
            </div>
            <button class="m-3 btn btn-primary" type="submit" title="Submit">Submit</button>
        </form>
    </div>
{% endblock %}

classroom/templates/classroom/index.html
{% extends 'core/base.html' %}

{% block title %}Quote{% endblock %}
    
{% block content %}
    <h1>Classroom</h1>
{% endblock %}

classroom/templates/classroom/newClassroom.html
{% extends 'core/base.html' %}

{% block title %}Classroom{% endblock %}
    
{% block content %}
<div>
    <form action="." method="post">
        <div class="form-group"></div>
            {% csrf_token %}
            <div class="mb-3">
                <label class="inline-block mb-2">Name:</label><br>
                {{ form.name }}
            </div>
            <div class="mb-3">
                <label class="inline-block mb-2">Passcode:</label><br>
                {{ form.passcode }}
            </div>
            <!-- Display any form errors -->
            {% for field in form %}
                {% for error in field.errors %}
                    <p style="color: red">{{ error }}</p>
                {% endfor %}
            {% endfor %}
        </div>
        <button class="m-3 btn btn-primary" type="submit">Create</button>
    </form>
</div>
{% endblock %}

classroom/templates/classroom/newQuiz.html
{% extends 'core/base.html' %}

{% block title %}Classroom{% endblock %}
    
{% block content %}

<style>
    .hidden {
        display: none;
    }
</style>

<div>
    <h1>Creating Quiz for: {{ lesson.title }}</h1>
    <form action="." method="post" enctype="multipart/form-data">
        <div class="form-group"></div>
            {% csrf_token %}
            {{ quiz_forms.management_form }}
            <div class="quiz-form-list">
            {% for quiz_form in quiz_forms %}
                <div class="quiz-form">
                    <hr>
                    {{ quiz_form.as_p }}
                </div>
            {% endfor %}
            </div>

            <div id="empty_quiz_form" class="hidden"><hr>{{ quiz_forms.empty_form.as_p }}</div>

            <button type="button" class="btn btn-primary" id="add-quiz">Add quiz</button>

            <button class="m-3 btn btn-primary" type="submit">Create</button>
            
            <!-- Display any form errors -->
            {% for field in form %}
                {% for error in field.errors %}
                    <p style="color: red">{{ error }}</p>
                {% endfor %}
            {% endfor %}
        </div>
    </form>
</div>

<script>
    const addquizButton = document.getElementById("add-quiz");
    const totalNewquizForms = document.getElementById("id_form-TOTAL_FORMS");
    const currentquizForms = document.getElementsByClassName("quiz-form");
    addquizButton.addEventListener("click", add_new_form)

    function add_new_form(event) {
        if (event) {
            event.preventDefault();
        }
        const currentquizFormCount = currentquizForms.length;
        const quizFormTarget = document.getElementsByClassName("quiz-form-list")[0];
        const emptyquizForm = document.getElementById("empty_quiz_form").cloneNode(true);
        emptyquizForm.setAttribute("class", "quiz-form");
        emptyquizForm.setAttribute("id", `objectve-form-${currentquizFormCount}`);
        const regex = new RegExp('__prefix__', 'g');
        emptyquizForm.innerHTML = emptyquizForm.innerHTML.replace(regex, currentquizFormCount);
        totalNewquizForms.setAttribute("value", currentquizFormCount + 1);
        quizFormTarget.append(emptyquizForm);
    }
</script>
{% endblock %}

classroom/templates/classroom/studentClassroom.html
{% extends 'core/base.html' %}

{% block title %}{{ classroom.name }}{% endblock %}
    
{% block content %}
    <h1 id="classroom-name" aria-label="classroom-name">{{ classroom.name }}</h1>
    <h2 id="teacher-name" aria-label="teacher-name">{{ classroom.teacher.user.username }}</h2>

    <div class="table-responsive">
        <table class="table table-striped table-dark table-hover styled-table" id="student-table" aria-label="student-table">
            <thead>
                <tr>
                    <th>Username</th>
                    <th>Overall Balance</th>
                </tr>
            </thead>
            <tbody>
                {% for student in classroomStudents %}
                {% if student.user.username == request.user.username %}
                <tr class="active-row">
                {% else %}
                <tr>
                {% endif %}
                    <td>{{ student.user.username }}</td>
                    <td>${{ student.total_value }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="table-responsive">
    <h2>Lessons</h2>
    <div class="d-grid gap-2 d-md-flex justify-content-center">
    <table class="table table-striped table-dark table-hover styled-table" id="lesson-table" aria-label="lesson-table">
        <thead>
            <tr>
                <th>Lesson</th>
                <th>Description</th>
                <th>Survey complete?</th>
                <th>Quiz complete?</th>
            </tr>
        </thead>
        <tbody>
            {% for lesson in classroomLessons %}
            <tr>
                <td><div class="fw-bold"><a href="{% url 'classroom:viewLesson' classroom.id lesson.id %}"><strong>{{ lesson.title }}</strong></a></div></td>
                <td>{{ lesson.description }}</td>
                <td>{% if lesson.completed_survey %}
                    Yes<i class="material-symbols-outlined text-success">Check_Circle</i>
                    {% else %}
                    <a href="{% url 'classroom:survey' classroom.id lesson.id %}" class="plain-link">No<i class="material-symbols-outlined text-danger">Unpublished</i></a>
                    {% endif %}
                </td>
                <td>{% if lesson.completed_quiz %}
                    <a href="{% url 'classroom:viewQuizResults' classroom.id lesson.id %}" class="plain-link">Yes<i class="material-symbols-outlined text-success">Check_Circle</i></a>
                    {% else %}
                    <a href="{% url 'classroom:takeQuiz' classroom.id lesson.id %}" class="plain-link">No<i class="material-symbols-outlined text-danger">Unpublished</i></a>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    </div>
    </div>

    <script>
        intro.setOptions({
            steps: [
                {
                    element: '#classroom-name',
                    intro: 'This is the name of your classroom.',
                    position: 'top'
                },
                {
                    element: '#teacher-name',
                    intro: 'This is the name of your teacher.',
                    position: 'top'
                },
                {
                    element: '#student-table',
                    intro: 'This is a table of all the students in your class and their overall balance.',
                    position: 'top'
                },
                {
                    element: '#lesson-table',
                    intro: 'This is a table of all the lessons in your class.',
                    position: 'top'
                }
            ]
        });
    </script>
{% endblock %}

classroom/templates/classroom/surveyResults.html
{% extends 'core/base.html' %}

{% block title %}Survey Results{% endblock %}
    
{% block content %}
    <h1>Survey results for {{ lesson.title }}</h1>
    <table class="table table-striped table-dark table-hover styled-table">
        <thead>
            <tr>
                <th>Content understanding</th>
                <th>Engagement</th>
                <th>Assessment accuracy</th>
                <th>Satisfaction</th>
                <th>Suggestions</th>
            </tr>
        </thead>
        <tbody>
            {% for result in surveyResults %}
                <tr>
                    <td>{{ result.get_content_understanding_display }}</td>
                    <td>{{ result.get_engagement_display }}</td>
                    <td>{{ result.assessment_accuracy }}</td>
                    <td>{{ result.get_satisfaction_display }}</td>
                    <td>{{ result.improvement_suggestions }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

classroom/templates/classroom/teacher.html
{% extends 'core/base.html' %}

{% block title %}Classroom{% endblock %}
    
{% block content %}
    <h1>Classroom</h1>
    <table class="table table-striped table-dark table-hover styled-table" id="class-table">
        <thead>
            <tr>
                <th>Class Name</th>
            </tr>
        </thead>
        <tbody>
            {% for classroom in teacher_classrooms %}
                <tr>
                    <td><a href="{% url 'classroom:teacherClassroom' classroom.id %}">{{ classroom.name }}</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    <a href="{% url 'classroom:newClassroom' %}" class="btn btn-primary">Create Classroom</a>

    <script>
        intro.setOptions({
        steps: [
                {
                    element: '#navbar',
                    intro: 'This is the navbar. It contains links to all the pages you can visit.',
                },
                {
                    element: '#class-table',
                    intro: 'This is the table of all the classrooms you are a teacher of. Click on a classroom to view it.',
                },
            ]
        })
    </script>
{% endblock %}

classroom/templates/classroom/viewLesson.html
{% extends 'core/base.html' %}

{% block title %}{{ lesson.title }}{% endblock %}
    
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <h1 aria-label="lesson-title">{{ lesson.title }}</h1>
            <p aria-label="lesson-description"><strong>{{ lesson.description }}</strong></p>
            {% for item in lesson_outline %}
            <hr>
            <p aria-label="learning objective"><strong>Learning objective:</strong> {{ item.learning_objective }}</p>
            <p aria-label="content">{{ item.content }}</p>
            {% endfor %}
        </div>
        <div class="col-6 col-md-4">
            {% if lesson.image %}
                <img src="{{ lesson.image.url }}" alt="{{ lesson.title }}-image" class="img-fluid rounded" style="height: 10rem; width: 10rem;">
            {% endif %}
            <div class="row">
                {% if not quizComplete %}
                <a aria-label="take-quiz-button" href="{% url 'classroom:takeQuiz' classroom.id lesson.id %}" class="btn btn-primary btn-block mt-2">Take Quiz</a>
                {% else %}
                <a aria-label="quiz-results-button" href="{% url 'classroom:viewQuizResults' classroom.id lesson.id %}" class="btn btn-primary btn-block mt-2">Show quiz results</a>
                {% endif %}
                {% if not surveyComplete %}
                <a aria-label="survey-button" href="{% url 'classroom:survey' classroom.id lesson.id %}" class="btn btn-warning btn-block mt-2">Take Survey</a>
                {% endif %}
            </div>
        </div>
    </div>
    <hr>
    <div class="row">
        <h1 class="col-md-8">Comments</h1>
        <div class="col-md-8">
            {% for comment in comments %}
            <div class="card mb-2 {% if comment.created_by == request.user %} bg-primary-subtle {% elif request.user.username in comment.content %} bg-warning-subtle {% else %} bg-secondary-subtle {% endif %}">
                <div class="card-body">
                    {% if comment.created_by.role == 'TEACHER' %}
                    <span class="material-symbols-outlined">
                        school
                    </span>
                    {% endif %}
                    <p class="card-text">{{ comment.content }}</p>
                    <p class="card-text"><small class="text-muted">Posted by {{ comment.created_by }} on {{ comment.created_at }}</small></p>
                </div>
            </div>
            {% endfor %}
        
            <div>
                <form action="." method="post">
                    <div class="form-group"></div>
                        {% csrf_token %}
                        <div class="">
                            {{ form.content }}
                        </div>
                        <!-- Display any form errors -->
                        {% for field in form %}
                            {% for error in field.errors %}
                                <p style="color: red">{{ error }}</p>
                            {% endfor %}
                        {% endfor %}
                    </div>
                    <button class="m-3 btn btn-primary" type="submit">Send</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}